// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuB8r-FuZ19Xe4OBscPG5PGb86quaYD_U',
    appId: '1:117149850724:web:fe1509e27f67036b13d371',
    messagingSenderId: '117149850724',
    projectId: 'ncueapp',
    authDomain: 'ncueapp.firebaseapp.com',
    storageBucket: 'ncueapp.appspot.com',
    measurementId: 'G-2FM98FLP44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1seViU-Yi66YoOkTwFvBLUd3SNXQgwo0',
    appId: '1:117149850724:android:d24bf83bd565118a13d371',
    messagingSenderId: '117149850724',
    projectId: 'ncueapp',
    storageBucket: 'ncueapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPzVC7xfFn8fyBBjVzul2Qtx7RJIW69EI',
    appId: '1:117149850724:ios:1f674806cb52214013d371',
    messagingSenderId: '117149850724',
    projectId: 'ncueapp',
    storageBucket: 'ncueapp.appspot.com',
    iosClientId: '117149850724-jnjeegthr2on0qn6m7ak40otrovkspb1.apps.googleusercontent.com',
    iosBundleId: 'com.ncueY.ncueYproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPzVC7xfFn8fyBBjVzul2Qtx7RJIW69EI',
    appId: '1:117149850724:ios:1f674806cb52214013d371',
    messagingSenderId: '117149850724',
    projectId: 'ncueapp',
    storageBucket: 'ncueapp.appspot.com',
    iosClientId: '117149850724-jnjeegthr2on0qn6m7ak40otrovkspb1.apps.googleusercontent.com',
    iosBundleId: 'com.ncueY.ncueYproject',
  );
}
